devices:
  adjust_period: 10
  capture:
    channels: 2
    extra_samples: 0
    filename: /dev/stdin
    format: S32LE
    read_bytes: 0
    skip_bytes: 0
    type: File
  capture_samplerate: 0
  chunksize: 1024
  enable_rate_adjust: false
  enable_resampling: false
  playback:
    channels: 2
    device: plughw:0,0
    format: S32LE
    type: Alsa
  queuelimit: 1
  rate_measure_interval: 1
  resampler_type: Synchronous
  samplerate: 44100
  silence_threshold: -60
  silence_timeout: 3
  stop_on_rate_change: false
  target_level: 0
filters:
  Volume:
    parameters:
      ramp_time: 200
    type: Volume
mixers:
  stereo:
    channels:
      in: 2
      out: 2
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -3
        inverted: true
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: -3
        inverted: true
        mute: false
pipeline:
- name: stereo
  type: Mixer
- channel: 0
  names:
  - Volume
  type: Filter
- channel: 1
  names:
  - Volume
  type: Filter
